name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_step: true
          script: |
            cd /home/ubuntu/instagram-server
            git pull origin main
            chmod +x mvnw
            ./mvnw clean package
            sudo fuser -k -n tcp 80 || true
            sudo java -jar target/*SNAPSHOT.jar > ./output.log 2>&1 &

